// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xumzfrtoyfqnotncedih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bXpmcnRveWZxbm90bmNlZGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDI1ODQsImV4cCI6MjA2NTQ3ODU4NH0.XMZ7heoPhUGVKwurHdOhfv-OQaHCWWI4z-OMGyqKukM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);